package inventory;




import EmployeeManagement.AttendanceEntry;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import login.Login;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raj
 */
public class InventoryMenu extends javax.swing.JFrame{

    /**
     * Creates new form MainMenu
     */
    private SalesItemShortage ss;
    private ProItemShortage ps;
    private int emID;
    
    public InventoryMenu(int emID) {
        this.emID=emID;
        ss=new SalesItemShortage();
        ps=new ProItemShortage();
        initComponents();
        //setIcon();
        setLocationRelativeTo(this);
        
        
        //for sales items
        if (ss.get_Data(0)!=0)
            saleShort.setEnabled(true);
        else
            saleShort.setEnabled(false);
        if (ss.get_Data(-1)!=0)
            saleOut.setEnabled(true);
        else
            saleOut.setEnabled(false);
        
        
        //for production items
        if (ps.get_Data(0)!=0)
            proShort.setEnabled(true);
        else
            proShort.setEnabled(false);
        if (ps.get_Data(-1)!=0)
            proShort.setEnabled(true);
        else
            proShort.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jButton5 = new javax.swing.JButton();
        labelCopyright = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        saleShort = new javax.swing.JButton();
        saleOut = new javax.swing.JButton();
        proShort = new javax.swing.JButton();
        proOut = new javax.swing.JButton();

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu12.setText("jMenu12");

        jMenuItem16.setText("jMenuItem16");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inventory Menu");
        setBackground(new java.awt.Color(222, 233, 253));
        setResizable(false);

        jButton5.setBackground(new java.awt.Color(222, 233, 253));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_remove.png"))); // NOI18N
        jButton5.setText("EXIT");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setIconTextGap(15);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        labelCopyright.setText("Copyrights ");
        labelCopyright.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelCopyright.setEnabled(false);
        labelCopyright.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jButton6.setBackground(new java.awt.Color(222, 233, 253));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 102));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_add.png"))); // NOI18N
        jButton6.setText("Supply");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setIconTextGap(15);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(222, 233, 253));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_add.png"))); // NOI18N
        jButton7.setText("Purchase");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setIconTextGap(15);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        saleShort.setBackground(new java.awt.Color(222, 233, 253));
        saleShort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saleShort.setForeground(new java.awt.Color(0, 51, 102));
        saleShort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_add.png"))); // NOI18N
        saleShort.setText("Sales item shortage");
        saleShort.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saleShort.setIconTextGap(15);
        saleShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleShortActionPerformed(evt);
            }
        });

        saleOut.setBackground(new java.awt.Color(222, 233, 253));
        saleOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saleOut.setForeground(new java.awt.Color(0, 51, 102));
        saleOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_add.png"))); // NOI18N
        saleOut.setText("Sale item out of Stock");
        saleOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saleOut.setIconTextGap(15);
        saleOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleOutActionPerformed(evt);
            }
        });

        proShort.setBackground(new java.awt.Color(222, 233, 253));
        proShort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proShort.setForeground(new java.awt.Color(0, 51, 102));
        proShort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_add.png"))); // NOI18N
        proShort.setText("Production item shortage");
        proShort.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proShort.setIconTextGap(15);
        proShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proShortActionPerformed(evt);
            }
        });

        proOut.setBackground(new java.awt.Color(222, 233, 253));
        proOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proOut.setForeground(new java.awt.Color(0, 51, 102));
        proOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_add.png"))); // NOI18N
        proOut.setText("Production item out of Stock");
        proOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proOut.setIconTextGap(15);
        proOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saleOut, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saleShort, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(labelCopyright)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addComponent(proShort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proOut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleShort, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proShort, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleOut, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proOut, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelCopyright)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Are you you want to exit?", "Confirmation", WIDTH);
        if (i == 0) {
            AttendanceEntry ae=new AttendanceEntry();
            ae.addDepatureAuto(emID);
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    //supply items to production unit
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SupplyProduction sp= new SupplyProduction();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    //get supply from out side 
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       GetSupplies frm= new GetSupplies();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    
    //for shortage of sales item
    private void saleShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleShortActionPerformed
        ss.get_Data(0);
        ss.setVisible(true);
    }//GEN-LAST:event_saleShortActionPerformed

     //for out of stock of sales item
    private void saleOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleOutActionPerformed
        ss.get_Data(-1);
        ss.setVisible(true);
    }//GEN-LAST:event_saleOutActionPerformed

    private void proShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proShortActionPerformed
        ps.get_Data(0);
        ps.setVisible(true);
    }//GEN-LAST:event_proShortActionPerformed

    private void proOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proOutActionPerformed
        ps.get_Data(-1);
        ps.setVisible(true);
    }//GEN-LAST:event_proOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelCopyright;
    private javax.swing.JButton proOut;
    private javax.swing.JButton proShort;
    private javax.swing.JButton saleOut;
    private javax.swing.JButton saleShort;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/vurologo.png")));
    }

    
   
}

